Bug fix for creating proactive engagement with disabled settings
aws-cloudformation/aws-cloudformation-resource-providers-shield pull request #59
Opened 2024-01-04 18:28 UTC by daewon-gong

*Description of changes:*
* Currently when a creating proactive engagement resource with disable settings creates the resource with enabled settings (this is a bug).
* Changed so that we read the request model and set ENABLED and DISABLED accordingly.

*Testing*
* Unit tests.

2024-01-04 18:48 UTC, ZigZagT requested changes

2024-01-04 18:51 UTC, ZigZagT commented on aws-shield-proactiveengagement/src/main/java/software/amazon/shield/proactiveengagement/CreateHandler.java
> +                                : HandlerHelper.disableProactiveEngagement("CreateHandler",
nvm I tried to call disable-proactive-engagement receptively on my account, looks like it won't throw error in this case

2024-01-05 19:47 UTC, daewon-gong commented on aws-shield-proactiveengagement/src/main/java/software/amazon/shield/proactiveengagement/CreateHandler.java
Addressed in next revision.

2024-01-05 23:10 UTC, ZigZagT approved these changes

2024-01-05 23:11 UTC, merged